// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/epiviz/configuration.js', ['epiviz.Configuration'], [], false);
goog.addDependency('../../../../src/epiviz/controllers/data-context.js', ['epiviz.controllers.DataContext'], ['goog.string.format'], false);
goog.addDependency('../../../../src/epiviz/controllers/master.js', ['epiviz.controllers.Master'], [], false);
goog.addDependency('../../../../src/epiviz/epiviz.js', ['epiviz'], ['epiviz.Configuration', 'epiviz.controllers.DataContext', 'epiviz.controllers.Master'], false);
